install.packages("Seurat")
library(Seurat)

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("slingshot")
library(slingshot)

BiocManager::install(c("tidyverse","tidymodels","Matrix","BUSpaRse"))
library(tidyverse)
# library(tidymodels)
library(Matrix)
library(BUSpaRse)
library(dplyr)

setwd("/Users/pbanerjee/Documents/CBU/CBU_Projects/Neuroscience/Camille_Single_cell/normoxia_1_5_merge/monocle_dim50/Seurat/")
# Imports sparse matrix generated by Cellranger. This is also sparse matrix
normox <- Read10X("/Users/pbanerjee/Documents/CBU/CBU_Projects/Neuroscience/Camille_Single_cell/normoxia_1_5_merge/1_5_merge_monocle3/outs/raw_feature_bc_matrix/")

# Create Seurat Object
# cells having less than 200 genes and genes detected in less than 3 cells are filtered out. 
normox_data <- CreateSeuratObject(normox,
                                  project = "Normox_10X_Seurat_SlingshotProject",
                                  assay = "RNA",
                                  min.cells = 3,
                                  min.features = 200,
                                  names.field = 1,
                                  names.delim = "_",
                                  meta.data = NULL
)

dim(normox_data)
#18349 82503
class(normox_data)
#GeneIDs
head(rownames(normox_data))
#Cellnames or CellIds
head(colnames(normox_data))
str(normox_data)
head(normox_data@meta.data)
# Visualize QC metrics as a violin plot
VlnPlot(normox_data, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)
# https://bustools.github.io/BUS_notebooks_R/slingshot.html
# Once cell_type is determinted we can color the graph with the cell annotations
ggplot(normox_data@meta.data, aes(nCount_RNA, nFeature_RNA)) +
  geom_point(size = 0.5) +
  scale_color_brewer(type = "qual", palette = "Set2") +
  scale_x_log10() +
  scale_y_log10() +
  theme_bw() +
  # Make points larger in legend
  guides(color = guide_legend(override.aes = list(size = 3))) +
  labs(x = "Total UMI counts", y = "Number of genes detected")


# FeatureScatter is typically used to visualize feature-feature relationships, but can be used
# for anything calculated by the object, i.e. columns in object metadata, PC scores etc.
plot2 <- FeatureScatter(normox_data, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot2

#Normalization
# normalizes the feature expression measurements for 
# each cell by the total expression, multiplies this by a scale factor (10,000 by default),
# and log-transforms the result. Normalized values are stored in normox_normalized[["RNA"]]@data.
normox_normalized <- NormalizeData(normox_data, normalization.method = "LogNormalize", scale.factor = 10000)
head(normox_normalized[["RNA"]]@data)
# Find Variable Features
# ook into highly variable genes that makes two group of cells different. 
# Seurat calculates highly variable genes and uses them in downstream data analysis.
# 2,000 features per dataset
normox_variable_feature <-FindVariableFeatures(normox_normalized, selection.method = "vst", nfeatures = 2000)
# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(normox_variable_feature), 10)
# plot variable features with and without labels
plot1 <- VariableFeaturePlot(normox_variable_feature)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot1 + plot2

#Scaling the data
all.genes <- rownames(normox_variable_feature)
# when I use all.genes to scale data the system crashes for memory limit
# normox_scaled <- ScaleData(normox_variable_feature, features = all.genes)
normox_scaled <- ScaleData(normox_variable_feature)

# Perform linear dimensional reduction
normox_red <- RunPCA(normox_scaled, npcs = 50, features = VariableFeatures(object = normox_scaled))
ElbowPlot(normox_red, ndims = 50)
# Examine and visualize PCA results a few different ways
print(normox_red[["pca"]], dims = 1:5, nfeatures = 5)
DimPlot(normox_red, reduction = "pca")
DimHeatmap(normox_red, dims = 1:15, cells = 500, balanced = TRUE)


normox_red_jackstraw <- JackStraw(normox_red, num.replicate = 100)
normox_red_jackstraw <- ScoreJackStraw(normox_red_jackstraw, dims = 1:50)
JackStrawPlot(normox_red_jackstraw, dims = 1:20)
ElbowPlot(normox_red_jackstraw)
ElbowPlot(normox_red, ndims = 50)


normox_neighbors <- FindNeighbors(normox_red_jackstraw, dims = 1:50)
normox_clusters <- FindClusters(normox_neighbors, resolution = 0.5)
# Look at cluster IDs of the first 5 cells
head(Idents(normox_clusters), 5)
#Run non-linear dimensional reduction (UMAP/tSNE)
# If you haven't installed UMAP, you can do so via reticulate::py_install(packages =
# 'umap-learn')
normox_clusters_umap <- RunUMAP(normox_clusters, dims = 1:50)
# note that you can set `label = TRUE` or use the LabelClusters function to help label
# individual clusters
DimPlot(normox_clusters_umap, pt.size=0.5, reduction = "umap", group.by = "seurat_clusters", label = TRUE)
saveRDS(normox_clusters_umap, file = "/Users/pbanerjee/Documents/CBU/CBU_Projects/Neuroscience/Camille_Single_cell/normoxia_1_5_merge/monocle_dim50/Seurat/normox_seurat.rds")
normox_clusters_umap$seurat_clusters

# find markers for every cluster compared to all remaining cells, report only the positive ones
normox.markers <- FindAllMarkers(normox_clusters_umap, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
write.table(normox.markers, "normox.markers.txt", sep="\t")
normox.markers$cluster

########################################################
########################################################
####### SLINGSHOT #######
#########################
########################################################
########################################################

head(Embeddings(normox_clusters_umap, reduction = "umap")[, 1:5])
sling_normox <- slingshot(Embeddings(normox_clusters_umap, "umap"),normox_clusters_umap$seurat_clusters, start.clus = 17, stretch = 0)

plot(reducedDim(sling_normox), pch = 16, cex = 0.5)
lines(sling_normox, lwd = 2, type = 'lineages', col = 'black')


colors <- rainbow(50, alpha = 1)
plot(reducedDims(sling_normox)$PCA, col = colors[cut(sce$slingPseudotime_1,breaks=50)], pch=16, asp = 1)
lines(SlingshotDataSet(sce), lwd=2)
